// ---------------------------------------------------------------------------
// Starter .ui file emitted by the integration wizard when the config's entry
// file does not exist yet. Uses only README-documented syntax: the Svelte-
// style single-file component shape, ui.mount(screen), a ui.signal, an
// on:click handler, and {signal} interpolation in the template.
// ---------------------------------------------------------------------------

export function renderStarterUi(displayWidth = 320, displayHeight = 240): string {
  // Keep text sizes sane on small mono panels (128×64 OLEDs).
  const compact = displayWidth <= 160 || displayHeight <= 160;
  const titleSize = compact ? 12 : 22;
  const countSize = compact ? 10 : 16;
  const buttonSize = compact ? 10 : 16;

  return [
    "<script>",
    "  // Starter screen generated by `npx @typecad/ui --config`.",
    "  // Edit freely — this is ordinary cuttlefish source, not generated output.",
    "",
    "  import { ui } from '@typecad/ui';",
    "",
    "  ui.mount(screen);",
    "",
    "  export const taps = ui.signal(0);",
    "",
    "  export function onTap() {",
    "    taps.set(taps() + 1);",
    "  }",
    "</script>",
    "",
    "<style>",
    "  screen {",
    "    background: #101418;",
    "    display: flex;",
    "    flex-direction: column;",
    "    align-items: center;",
    "    justify-content: center;",
    "    gap: 16px;",
    "  }",
    `  #title { color: #e8eef2; font-size: ${titleSize}px; }`,
    `  #count { color: #38bdf8; font-size: ${countSize}px; }`,
    "  #tap {",
    `    padding: 10px 24px;`,
    "    border-radius: 8px;",
    "    background: #1f6feb;",
    "    color: #ffffff;",
    `    font-size: ${buttonSize}px;`,
    "  }",
    "</style>",
    "",
    "<screen>",
    "  <text id=\"title\">@typecad/ui is running</text>",
    "  <text id=\"count\">taps: {taps}</text>",
    "  <button id=\"tap\" on:click={onTap}>Tap me</button>",
    "</screen>",
    "",
  ].join("\n");
}
